### ISSUE TITLE
NavbarItems posible enabled and disable

### ISSUE THREAD

**Issue by jmlpinaEtec** [Servoy/svyNavigation#1]
Is there a posibility to enable or disable the navbarItems in production mode?

thanks for this big project

**Comment by paronne** [comment]
Hi,

thank you for your feedback. 
You mean to disabled the navbar items depending on some conditions ? i can imagine i common use case is to disable a specific menu or navbar item if the logged user doesn't have the permission for it. 
The items can be disabled or removed any time from the navbar element.
If is related to user permissions i would disable them, or even better skip them, in the loadNavbarItems function

```
function loadNavbarItems() {
	var menuItems = [];

        // skip the navbar item if user has no permissions to it
	if ( userHasPermissionsToAdminSettings ) {
	      menuItem = elements.navbar.createMenuItem('User', 'ADMIN-SETTINGS', 'RIGHT');
	      menuItem.displayType = 'MENU_ITEM';
	      menuItems.push(menuItem);
        }

	// user menu item
	menuItem = elements.navbar.createMenuItem('User', 'USER-SETTINGS', 'RIGHT');
	menuItem.displayType = 'MENU_ITEM';
	menuItem.iconName = 'fas fa-user';

        // add a sub-item
	var logoutMenuItem = elements.navbar.createMenuItem('Logout', 'LOGOUT');
	menuItem.subMenuItems = [logoutMenuItem];
	menuItems.push(menuItem);

	return menuItems;
}
```

If you want still to show it and just to disabled it instead you can set the property enabled = false for the navbar item

```
	      menuItem = elements.navbar.createMenuItem('User', 'ADMIN-SETTINGS', 'RIGHT');
	      menuItem.displayType = 'MENU_ITEM';
	      if ( !userHasPermissionsToAdminSettings ) {
                       menuItem.enabled = false;
              }
	      menuItems.push(menuItem);
```

Further you can interact with the navbar item any other moment within your form. You can read more about the Navbar at this wiki page: https://github.com/Servoy/bootstrapextracomponents/wiki/Navbar

Regards,
Paolo

**Comment by jmlpinaEtec** [comment]
Ok.  I was looking for navBar properties in svyNavigation project. 
Thanks a lot
