### ISSUE TITLE
Wiki text needs some improvement

### ISSUE THREAD

**Issue by costescuandrei** [Servoy/svyNavigation#5]
1. The wiki page is not very accurate in the text from quick start (suggests you can choose any form from the module as base form - which is not the case
2. _sidenav _element doesn’t specify "from the form you created extending the base form, component ...". I think “set the first form to be viewed” could make one think of the firstform in the solution properties) - although screenshots help.

**Comment by paronne** [comment]
For now there is only 1 template : svyNavigationUX$Sidenav
Changed the wiki to reference svyNavigationUX$Sidenav
