### ISSUE TITLE
Using the function scopes.svyNavigation.open(_nav_item, dataToShow, dataSelectionType) in a forms that never has been loaded does not work

### ISSUE THREAD

**Issue by juanetec** [Servoy/svyNavigation#9]
Hi, using the function scopes.svyNavigation.open(_nav_item, _fs, null) on a process.
The _nav_item is a name of a forms that hasn't been loaded.
The _fs is a foundset that I want to show.
The first time it doesn't work properly, because it doesn't show the foundset that I want, it show the first 200 items.
If you launch that process again it work perfect.

Un Saludo

Juan Ramírez

**Comment by paronne** [comment]
Hi Juan,

are you testing this in the sample solution where the grid form extends the baseTableAdvanced form ?
Please note such base form restore the filter state, and therefore the queryed foundset, upon firstShow; therefore would override the loadRecords from the scopes.svyNavigation.open upon firstShow.

```
	// restore toolbar filter state on first show
	if (firstShow) {
		var filterState = scopes.svyProperties.getUserPropertyValue(propertyKey, 'filter-state');
		if (filterState) {
			var toolbarState = JSON.parse(filterState);
			toolbarFilter.restoreToolbarFiltersState(toolbarState);
		}
	}
```

**Comment by juanetec** [comment]
Ok Paolo, you are right, my problem was with the toolbarFilter.restoreToolbarFiltersState(toolbarState);

Thanks
